ios/Mukkaebie/Mukkaebie.xcodeproj/project.pbxproj, ios/Mukkaebie/Mukkaebie/AppDelegate.swift, ios/Mukkaebie/Mukkaebie/Extension.swift, ios/Mukkaebie/Mukkaebie/Info.plist, ios/Mukkaebie/Mukkaebie/MainHeaderCollectionReusableView.swift, ios/Mukkaebie/Mukkaebie/MainViewController.swift, ios/Mukkaebie/Mukkaebie/StoreListStoryboard.storyboard, ios/Mukkaebie/Mukkaebie/StoreListTableViewCell.swift, ios/Mukkaebie/Mukkaebie/StoreListViewController.swift
가게리스트 뷰컨트롤러&스토리보드 추가
가게리스트 테이블뷰 레이아웃
임시 data로 구현
=>  가게리스트 테이블뷰 추가

web/ranking.html, web/src/yg.css
먹깨비 랭킹 그래프 구현하며 yg.css 좀 만졌음. 확인 부탁
=> Ranking 페이지 1차 완료

web/src/index.js, web/src/main.css, web/src/yg.css, web/src/yg.js, web/store.html
지점 페이지 탭기능 구현 완료, 
지점 정보에 관한 미디어 쿼리부분 merge시 조정 필요
=> 지점 페이지 탭기능 구현 및 적용 완료

web/ranking.html, web/src/index.js, web/src/main.css, web/src/yg.css, web/src/yg.js, web/store.html
=> 먹깨비 랭킹 데이터 바인딩 실험 완료

web/src/chart.css, web/store.html
=> 리뷰 서버통신 완료, 도넛그래프 퍼센티지 디스플레이 완료, 도넛그래프 미디어쿼리 모바일용 필요

web/src/yg.css, web/src/yg.js, web/store.html
리뷰 작성시 리뷰디비 포스트후 자동으로 돔 조작완료
현재 주문시 디비에 포스트 가능, 먹깨비 그래프 조작 작업 필요
=> Feature review post

ios/Mukkaebie/Mukkaebie.xcodeproj/project.pbxproj, ios/Mukkaebie/Mukkaebie.xcworkspace/contents.xcworkspacedata, ios/Mukkaebie/Mukkaebie/AppDelegate.swift, ios/Mukkaebie/Mukkaebie/Info.plist, ios/Mukkaebie/Mukkaebie/ModelStores.swift, ios/Mukkaebie/Mukkaebie/ModelUsers.swift, ios/Mukkaebie/Mukkaebie/NetworkStore.swift, ios/Mukkaebie/Mukkaebie/NetworkUser.swift, ios/Mukkaebie/Mukkaebie/StoreDetailViewController.swift, ios/Mukkaebie/Mukkaebie/URLpath.swift, ios/Mukkaebie/Podfile, ios/Mukkaebie/Podfile.lock
유저모델 구성
스토어모델 구성
네트워킹 data request
=> 모델 & 서버네트워킹 구성

ios/Mukkaebie/Mukkaebie/MainViewController.swift, ios/Mukkaebie/Mukkaebie/MenuViewController.swift, ios/Mukkaebie/Mukkaebie/MukkaebieRankViewController.swift, ios/Mukkaebie/Mukkaebie/StoreDetail.storyboard, ios/Mukkaebie/Mukkaebie/StoreDetailViewController.swift
레이아웃에 있던 오토레이아웃 제거한 후
높이로 일일이 조정해줬습니다. 
또한 컨트롤 뷰를 새로 만들게 해서 새로운 뷰를 넣게 했습니다.
=> storeDetail 뷰에서 생긴 터치 오류 디버그

ios/Mukkaebie/Mukkaebie/AppDelegate.swift, ios/Mukkaebie/Mukkaebie/ModelOrders.swift, ios/Mukkaebie/Mukkaebie/ModelStores.swift, ios/Mukkaebie/Mukkaebie/ModelUsers.swift, ios/Mukkaebie/Mukkaebie/NetworkOrder.swift
model stores 안에 orders parameter를 넣었습니다.
=> ModelStores 안에 orders parameter 넣음

ios/Mukkaebie/Mukkaebie/NetworkOrder.swift, ios/Mukkaebie/Mukkaebie/StoreDetailViewController.swift, ios/Mukkaebie/Mukkaebie/StoreList.storyboard, ios/Mukkaebie/Mukkaebie/StoreListViewController.swift
storeList에서 선택된 modelStore를 다음 뷰에 가져온다.
modelStore에 있는 ID를 이용하여 orders를 가져온다.
실제 가게에 대해 아직 영균이 형이 order데이타를 넣지 않았기 때문에
지금은 101010으로 되어 있음
=> storeDetail에서 orders 정보 가져오기

ios/Mukkaebie/Mukkaebie/ModelOrders.swift, ios/Mukkaebie/Mukkaebie/ModelStores.swift, ios/Mukkaebie/Mukkaebie/NetworkOrder.swift, ios/Mukkaebie/Mukkaebie/StoreDetailViewController.swift
네트워크 주문 추가 함수 구현하고
modelstores에서 메뉴도 가져오게 함
=> Networking 주문 추가 함수 구현

web/src/css/chart.css
=> Feature chart

ios/Mukkaebie/Mukkaebie/MenuViewController.swift, ios/Mukkaebie/Mukkaebie/ModelOrders.swift, ios/Mukkaebie/Mukkaebie/StoreDetailViewController.swift
서버에서 메뉴 주문 수를 세서 그래프를 만들게 했습니다.
=> 그래프에 데이타 적용

ios/Mukkaebie/Mukkaebie.xcodeproj/project.pbxproj, ios/Mukkaebie/Mukkaebie/Info.plist, ios/Mukkaebie/Mukkaebie/ModelStores.swift, ios/Mukkaebie/Mukkaebie/ModelUsers.swift, ios/Mukkaebie/Mukkaebie/NetworkOrder.swift, ios/Mukkaebie/Mukkaebie/NetworkUser.swift, ios/Mukkaebie/Mukkaebie/StoreListViewController.swift, ios/Mukkaebie/Podfile, ios/Mukkaebie/Podfile.lock
info.plist 수정
스토어 네트워크 서버 바뀐 것에 따라 수정
alamofireimage 수정
=> 네트워크 모델 수정

transactionApi/server.js, web/index.html, web/src/index.js, web/src/scss/storeList.scss, web/storeList.html
=> 스토어 리스트 페이지 및 렌더링 완료

ios/Mukkaebie/Mukkaebie/MukkaebieRank.storyboard, ios/Mukkaebie/Mukkaebie/MukkaebieRankViewController.swift, ios/Mukkaebie/Mukkaebie/StoreTestViewController.swift, ios/Mukkaebie/Mukkaebie/circleView.swift, ios/Mukkaebie/Mukkaebie/segment.swift
테이블뷰 오토레이아웃
먹깨비랭킹뷰 높이 조절
먹깨비랭킹 디자인 교체 작업 후 디테일수정예정
=> 테이블뷰 서브뷰 오토레이아웃

ios/Mukkaebie/Mukkaebie/NetworkStore.swift, ios/Mukkaebie/Mukkaebie/StoreDetail.storyboard, ios/Mukkaebie/Mukkaebie/StoreList.storyboard, ios/Mukkaebie/Mukkaebie/StoreListMenuBarCollectionViewCell.swift, ios/Mukkaebie/Mukkaebie/StoreListTableViewCell.swift, ios/Mukkaebie/Mukkaebie/StoreListViewController.swift
store list에서 카테고리 선택하고
서버에서 그에 맞는 store list 가져오도록 구현
각종 디버그
=> Store list 카테고리 구현

ios/Mukkaebie/Mukkaebie/StoreListMenuBarCollectionViewCell.swift, ios/Mukkaebie/Mukkaebie/StoreListViewController.swift
스토어 리스트 메뉴바 셀선택 리팩토링
셀 선택 오류 디버깅
=> collection메뉴바 디버깅

ios/Mukkaebie/Mukkaebie.xcodeproj/project.pbxproj, ios/Mukkaebie/Mukkaebie/Info.storyboard, ios/Mukkaebie/Mukkaebie/InfoViewController.swift, ios/Mukkaebie/Mukkaebie/StoreListViewController.swift, ios/Mukkaebie/Mukkaebie/StoreTestViewController.swift, ios/Mukkaebie/Mukkaebie/segment.swift
=> info page 구현

ios/Mukkaebie/Mukkaebie/Base.lproj/Main.storyboard, ios/Mukkaebie/Mukkaebie/MainCollectionViewCell.swift, ios/Mukkaebie/Mukkaebie/MainViewController.swift, ios/Mukkaebie/Mukkaebie/StoreListViewController.swift, ios/Mukkaebie/Mukkaebie/segment.swift
메인에서 카테고리 선택시 다음 뷰에서 카테고리 적용되게 구현
=> 카테고리 변경 구현

web/index.html, web/src/scss/store.scss, web/src/upload.js
=> Feature mkb upload 먹깨비 사진 업로드 기능

web/src/index.js, web/src/scss/store.scss, web/src/store.js
=> 가게 리스트 - 가게 - 탭 연결

web/index.html, web/src/scss/main.scss, web/src/scss/store.scss, web/src/store.js
먹깨비 코멘트 레이아웃을 만들고 업소 리스트에서 카드와 카드 사이를 누르면 에러가 나는 버그를 수정했습니다.
=> Feature MKBcomment

ios/Mukkaebie/Mukkaebie/MukkaebieRank.storyboard, ios/Mukkaebie/Mukkaebie/SegmentView.swift, ios/Mukkaebie/Mukkaebie/StoreTestViewController.swift, ios/Mukkaebie/Mukkaebie/circleView.swift, ios/Mukkaebie/Mukkaebie/segment.xib, ios/Mukkaebie/Mukkaebie/statusTableViewCell.xib
=> segment 디테일 조절

ios/Mukkaebie/Mukkaebie/MenuViewController.swift, ios/Mukkaebie/Mukkaebie/MukkaebieRank.storyboard, ios/Mukkaebie/Mukkaebie/Review.storyboard, ios/Mukkaebie/Mukkaebie/ReviewTableViewController.swift, ios/Mukkaebie/Mukkaebie/StoreDetail.storyboard, ios/Mukkaebie/Mukkaebie/StoreTestViewController.swift, ios/Mukkaebie/Mukkaebie/TabSubviewTableViewCell.swift
tab subview의 컨텐츠에 따라 높이가 바뀌도록 만들었습니다.
=> tab subview height 조절

ios/Mukkaebie/Mukkaebie/SegmentView.swift, ios/Mukkaebie/Mukkaebie/StoreTestViewController.swift, ios/Mukkaebie/Mukkaebie/segment.swift, ios/Mukkaebie/Mukkaebie/segment.xib
=> 높이 바뀌면 헤더 사라지는 버그 해결

ios/Mukkaebie/Mukkaebie/Info.storyboard, ios/Mukkaebie/Mukkaebie/MenuView.storyboard, ios/Mukkaebie/Mukkaebie/MukkaebieRank.storyboard, ios/Mukkaebie/Mukkaebie/StoreDetail.storyboard, ios/Mukkaebie/Mukkaebie/StoreList.storyboard, ios/Mukkaebie/Mukkaebie/StoreListTableViewCell.swift, ios/Mukkaebie/Mukkaebie/StoreListViewController.swift
=> 리스트 & 먹깨비 오토레이아웃

ios/Mukkaebie/Mukkaebie/StoreTestViewController.swift
=> 메뉴 없는 업소 해결

web/index.html, web/src/index.js, web/src/scss/store.scss, web/src/scss/storeList.scss, web/src/store.js
=> Feature make real order

ios/Mukkaebie/Mukkaebie/PieChart.swift
메뉴 파이 그래프 버튼으로 바꾸고 레이아웃 수정했습니다.
=> 메뉴 파이 그래프 버튼 추가 및 레이아웃 수정

web/index.html, web/src/store.js
StoreInfo  클래스 Promise 패턴 적용, 탬플릿 적용
=> General web code refactoring

ios/Mukkaebie/Mukkaebie/StoreListViewController.swift
=> 네비게이션 클릭한 메뉴에 따라 업데이트 되도록 수정

ios/Mukkaebie/Mukkaebie.xcodeproj/project.pbxproj, ios/Mukkaebie/Mukkaebie/CartPaymentViewController.swift, ios/Mukkaebie/Mukkaebie/MenuViewController.swift, ios/Mukkaebie/Mukkaebie/StoreDetail.storyboard
=> 장바구니 ios 추가

ios/Mukkaebie/Mukkaebie/StoreTestViewController.swift
=> 메뉴 없는 업소 오류 해결

ios/Mukkaebie/Mukkaebie/ModelOrders.swift, ios/Mukkaebie/Mukkaebie/MukkaebieRankViewController.swift, ios/Mukkaebie/Mukkaebie/StoreDetailViewController.swift, ios/Mukkaebie/Mukkaebie/StoreTestViewController.swift
order로 부터 top3 유저를 구하고 mukkaebierank view에 전달
=> Mukkaebie rank top3 유저 구현

ios/Mukkaebie/Mukkaebie/CartPaymentViewController.swift, ios/Mukkaebie/Mukkaebie/MenuViewController.swift, ios/Mukkaebie/Mukkaebie/MukkaebieRank.storyboard, ios/Mukkaebie/Mukkaebie/MukkaebieRankViewController.swift, ios/Mukkaebie/Mukkaebie/PieChart.swift, ios/Mukkaebie/Mukkaebie/StoreTestViewController.swift
=> 먹깨비 랭킹 애니메이션 & 파이차트 디버깅추가

web/src/scss/store.scss, web/src/store.js
=> Feature storelistpage

ios/Mukkaebie/Mukkaebie/MukkaebieRankViewController.swift
=> Networking

ios/Mukkaebie/Mukkaebie/Base.lproj/Main.storyboard, ios/Mukkaebie/Mukkaebie/CartPaymentViewController.swift, ios/Mukkaebie/Mukkaebie/Extension.swift, ios/Mukkaebie/Mukkaebie/StoreDetail.storyboard, ios/Mukkaebie/Mukkaebie/StoreTestViewController.swift
=> 알러트 추가 및 메인 수정

ios/Mukkaebie/Mukkaebie.xcodeproj/project.pbxproj, ios/Mukkaebie/Mukkaebie/Info.plist, ios/Mukkaebie/Mukkaebie/MukkaebieRankViewController.swift, ios/Mukkaebie/Mukkaebie/NetworkImagePicker.swift, ios/Mukkaebie/Mukkaebie/StoreTestViewController.swift, ios/Mukkaebie/Mukkaebie/URLpath.swift
image picker에서 사진 선택하면 서버에 이미지 업로드하고 스토어 mkb에 이미지 포스트합니다.
=> image picker 업로드 구현

web/index.html, web/src/index.js, web/src/scss/chart.scss, web/src/scss/main.scss, web/src/scss/store.scss, web/src/store.js
=> Feature mkb uploadv3

web/index.html, web/src/index.js, web/src/scss/chart.scss, web/src/scss/store.scss, web/src/scss/storeList.scss, web/src/store.js
=> Feature store detail

web/index.html, web/src/scss/main.scss
=> 태블릿에서 copyright와 통신판매 관련 안내가 겹쳐보이는 에러 수정

web/src/js/Util.js, web/src/scss/store.scss
=> 주문하기 클릭시 현재 yOffset에서 맨위로 서서히 스크롤되도록 만듦

web/src/js/Graph.js, web/src/scss/chart.scss
=> 도넛그래프 css hover effect 적용

web/index.html, web/src/scss/main.scss
loginMenu node를 header 밖으로 빼서 해결
=> 모바일에서 로그인 메뉴 안보이는 버그 수정

ios/Mukkaebie/Mukkaebie/MukkaebieRankViewController.swift
=> Mukkaebie rank 뷰 구조 정리

ios/Mukkaebie/Mukkaebie.xcodeproj/project.pbxproj, ios/Mukkaebie/Mukkaebie/MenuViewController.swift, ios/Mukkaebie/Mukkaebie/ModelStores.swift, ios/Mukkaebie/Mukkaebie/MukkaebieRank.storyboard, ios/Mukkaebie/Mukkaebie/MukkaebieRankViewController.swift, ios/Mukkaebie/Mukkaebie/PieChart.swift, ios/Mukkaebie/Mukkaebie/StoreDetailViewController.swift
=> Mukkaebie rank 파이 그래프 수정

ios/Mukkaebie/Mukkaebie/LaunchScreen.swift, ios/Mukkaebie/Mukkaebie/LaunchView.xib, ios/Mukkaebie/Mukkaebie/MainViewController.swift
=> Main 런칭 뷰 오토레이아웃 및 애니메이션 구현

ios/Mukkaebie/Mukkaebie/AppDelegate.swift, ios/Mukkaebie/Mukkaebie/Base.lproj/Launch.storyboard, ios/Mukkaebie/Mukkaebie/Base.lproj/Main.storyboard, ios/Mukkaebie/Mukkaebie/Info.plist, ios/Mukkaebie/Mukkaebie/LaunchScreen.swift, ios/Mukkaebie/Mukkaebie/MainViewController.swift, ios/Mukkaebie/Mukkaebie/MenuView.storyboard, ios/Mukkaebie/Mukkaebie/MenuViewController.swift, ios/Mukkaebie/Mukkaebie/MukkaebieRank.storyboard, ios/Mukkaebie/Mukkaebie/MukkaebieRankViewController.swift, ios/Mukkaebie/Mukkaebie/PieChart.swift, ios/Mukkaebie/Mukkaebie/StoreDetail.storyboard, ios/Mukkaebie/Mukkaebie/StoreDetailViewController.swift
=> 먹깨비 비 애니메이션 추가
